'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WeeklyScoringUpdate

    '''<summary>
    '''TeamsByGameTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamsByGameTable1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Nothing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents [Nothing] As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Status1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1A As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing1B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1B As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
